# Generated by Django 3.2.1 on 2021-05-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0002_remove_product_rating'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rating', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_title',
            field=models.CharField(max_length=254),
        ),
    ]
