# Generated by Django 3.2.1 on 2021-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='created_by',
            field=models.CharField(default='', max_length=254),
        ),
    ]
